build:
    nodes:
        coverage:
            tests:
                override:
                    - npm run cleandb
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
